%% Gripper Forces and Torques 
%
%  Author: Adam Schonewille
%  MASc Student, University of Toronto
%
%  Start Date: January 6th 2020
%  Last Editted: January 7th 2020
%

% This script is for calculating the forces and torques acting on the wrist
% and finger magnets of our microsurgical tool when a dipole moment is
% actuatating the device

%% Define simulation parameters
% Gripper in this orientation:
%                    ___               _________
%          _____----[___]             |    |    |
% O-------[__|__]    ___              |    |    |
% ^             ----[___]             |____|____|
% origin
%       
%          x ---->
%

clear all; close all; clc; % ensure there are no variables or open plots

% Magnetic moment magnitude and direction for components
Br = 1.42;  %[T]
mu_0 = pi*4e-7; %[H/m]
wrist_vol    = (1/1000^3) * 3.46*1.59*1.59; %[m^3]
finger_vol   = (1/1000^3) * 3.00*1.00*1.00; %[m^3]
actuator_vol = (1/1000^3) * (4.00*25.4)^3;  %[m^3]
% Calculates magnetic moment from remenance and volume of magnets
wrist_mag    = 1/mu_0 * Br * wrist_vol;    %[Am^2]
finger_mag   = 1/mu_0 * Br * finger_vol;   %[Am^2]
actuator_mag = 1/mu_0 * Br * actuator_vol; %[Am^2]
m_wrist    =    wrist_mag * [1  0  0]'; %[Am^2]
m_finger1  =   finger_mag * [0  1  0]'; %[Am^2]
m_finger2  =   finger_mag * [0 -1  0]'; %[Am^2]
m_actuator = actuator_mag * [1  0  0]'; %[Am^2]
% Position of magnets (centered)
p_wrist    = 1/1000 * [ 10  0  0]'; %[m]
p_finger1  = 1/1000 * [ 22  3  0]'; %[m]
p_finger2  = 1/1000 * [ 22 -3  0]'; %[m]
p_actuator = 1/1000 * [150  0  0]'; %[m]
LeverArm_fingers = 10/1000; %[m]
%% Forces and Torques
% All forces and torques are acting on the body they describe from the 
% actuator magnet 
% Theory and Linear Algebra/Matrices used are based off the paper "Minimum
% Bounds on the Number of Electomagnets Required for Remote Magnetic
% Manipulation" By Andrew J. Petruska and Bradley Nelson. 
% Calculate the vector of 5 Gradients dBx/dx, dBx/dy ... dBy/dz at the
% different magnet positions
G_wrist = dipoleGradient((p_wrist-p_actuator),m_actuator);
G_finger1 = dipoleGradient((p_finger1-p_actuator),m_actuator);
G_finger2 = dipoleGradient((p_finger2-p_actuator),m_actuator);
% Utilize the rearranged force matrix
Force_wrist = forceMatrix(m_wrist) * G_wrist;
Force_finger1 = forceMatrix(m_finger1) * G_finger1;
Force_finger2 = forceMatrix(m_finger2) * G_finger2;
% Calculate the magnetic field at the tool magnets that are generated by 
% the actuator magnet assuming it can be accurately represented by a 
% dipole field.
B_wrist = dipoleField((p_wrist-p_actuator),m_actuator);
B_finger1 = dipoleField((p_finger1-p_actuator),m_actuator);
B_finger2 = dipoleField((p_finger2-p_actuator),m_actuator);
% Use magnetic field and the skew symmetric matrix to calculate the torques
% that are applied to the tool magnets
Torque_wrist = skew(m_wrist) * B_wrist;
Torque_finger1 = skew(m_finger1) * B_finger1;
Torque_finger2 = skew(m_finger2) * B_finger2;
% The force generated at the tool's fingertips can be calculated using the
% relationship between force, torque and lever arm:
% T = F x r,   where r is measured from the device and torque is know from
% our calculations. F is assumed to be perpendicular to the finger lengths
Force1_from_torque = Torque_finger1(3)/LeverArm_fingers;
Force2_from_torque = Torque_finger2(3)/LeverArm_fingers;

%% Plotting for visualization of Results
% Combine for shorthand when plotting
p = [p_wrist p_finger1 p_finger2];
f = [Force_wrist Force_finger1 Force_finger2];
% set plots to laTex font
set(groot, 'defaultAxesTickLabelInterpreter','latex');
set(groot, 'defaultLegendInterpreter','latex');
set(0,'defaulttextInterpreter','latex');

markerSize = 5;
lineWidth = 2;
            
figure(1)
hold on
quiver(p(1,:),p(2,:),f(1,:),f(2,:),0,'b',"MarkerSize", markerSize,"LineWidth",lineWidth)
quiver(p(1,:),p(2,:),[0 0 0],[0 Force1_from_torque Force2_from_torque],0,'r',"MarkerSize", markerSize,"LineWidth",lineWidth)

% Mark out the positions of the magnets and actuator
plot(p(1,:),p(2,:),'ko',"MarkerSize", markerSize,"LineWidth",lineWidth)
plot(p_actuator(1),p_actuator(2),'ko',"MarkerSize", markerSize,"LineWidth",lineWidth)
% Draw a box to outline each magnet's footprint for context
s = actuator_vol^(1/3); % Actuator
act_x1 = p_actuator(1)-s/2;
act_x2 = p_actuator(1)+s/2;
act_y1 = p_actuator(2)-s/2;
act_y2 = p_actuator(2)+s/2;
plot([act_x1,act_x2,act_x2,act_x1,act_x1],[act_y1,act_y1,act_y2,act_y2,act_y1],'k')
% Wrist magnet
wrist_x1 = p_wrist(1)-3.46/2/1000;
wrist_x2 = p_wrist(1)+3.46/2/1000;
wrist_y1 = p_wrist(2)-1.59/2/1000; 
wrist_y2 = p_wrist(2)+1.59/2/1000;
plot([wrist_x1,wrist_x2,wrist_x2,wrist_x1,wrist_x1],[wrist_y1,wrist_y1,wrist_y2,wrist_y2,wrist_y1],'k')
% Finger magnets
finger_x1 = p_finger1(1)-3.00/2/1000;
finger_x2 = p_finger1(1)+3.00/2/1000;
finger_y1 = p_finger1(2)-1.00/2/1000;
finger_y2 = p_finger1(2)+1.00/2/1000;
plot([finger_x1,finger_x2,finger_x2,finger_x1,finger_x1],[finger_y1,finger_y1,finger_y2,finger_y2,finger_y1],'k')
plot([finger_x1,finger_x2,finger_x2,finger_x1,finger_x1],-[finger_y1,finger_y1,finger_y2,finger_y2,finger_y1],'k')

xlabel("X Direction [m]")
ylabel("Y Direction [m]" )
xlim([0 0.150])
ylim([-0.055 0.055])
title("Forces acting on microgripper due to an applied dipole moment")
legend("Forces due to Gradients", "Forces due to Torques", "Location", "Northeast")
hold off
